= TLDR Blog UI (Antora)
// Settings:
:experimental:
:hide-uri-scheme:
// Project URLs:
:url-project: https://github.com/groknull/tldr-ui
:url-preview: https://tldr.groknull.dev/
:url-ci-pipelines: {url-project}/actions
:img-ci-status: {url-project}/actions/workflows/ci.yml/badge.svg
// External URLs:
:url-antora: https://antora.org
:url-antora-docs: https://docs.antora.org
:url-git: https://git-scm.com
:url-git-dl: {url-git}/downloads
:url-gulp: http://gulpjs.com
:url-opendevise: https://opendevise.com
:url-nodejs: https://nodejs.org
:url-source-maps: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

image:{img-ci-status}[CI Status (GitLab CI), link={url-ci-pipelines}]

This project is the UI source for the https://tldr.groknull.dev/[TLDR blog], built with {url-antora}[Antora].
It is a fork of the Antora Default UI and retains the original structure as a starting point for customization.
If you are looking for the upstream default UI, see {url-preview}.

== Use this UI bundle

This repository contains the UI bundle for the TLDR blog. Build it locally and point your Antora playbook at the bundle.

[source,yaml]
----
ui:
  bundle:
    url: ./build/ui-bundle.zip
    snapshot: true
----

Run `gulp bundle` from link:.[this repository] to generate the bundle in `build/ui-bundle.zip`.
The `snapshot` flag tells Antora to fetch the UI when the `--fetch` command-line flag is present.

== Enable Article/Post Functionality

This theme includes built-in support for displaying blog articles and posts.
To enable this functionality, you need to use the included Antora extension.

=== Quick Start

. Download the `posts-extension.js` file from the link:{url-project}/releases/latest[latest release] or copy it from the `extensions/` folder
. Place it in your documentation project (e.g., `extensions/posts-extension.js`)
. Register the extension in your `antora-playbook.yml`:
+
[source,yaml]
----
antora:
  extensions:
    - ./extensions/posts-extension.js
----

. Mark your article pages with the required attributes:
+
[source,asciidoc]
----
= My Blog Post
:page-role: article
:page-date: 2026-01-07
:description: A short summary of this article

Your article content here...
----

The extension will automatically collect all pages marked with `page-role: article` and make them available to the theme's article listing features.

For complete documentation including all available attributes, troubleshooting, and customization options, see link:extensions/README.adoc[].

== Development Quickstart

This section offers a basic tutorial to teach you how to set up the UI project, preview it locally, and bundle it for use with Antora.
A more comprehensive tutorial can be found in the documentation at {url-antora-docs}.

=== Prerequisites

To preview and bundle the UI, you need the following software on your computer:

* {url-git}[git] (command: `git`)
* https://mise.jdx.dev/[mise] (command: `mise`)
* {url-nodejs}[Node.js] via mise (commands: `node` and `npm`)
* {url-gulp}[Gulp CLI] via mise (command: `gulp`)

==== git

First, make sure you have git installed.

 $ git --version

If not, {url-git-dl}[download and install] the git package for your system.

==== mise

Install the toolchain defined in `mise.toml`:

 $ mise install

Verify the tools are available:

 $ node --version
 $ npm --version
 $ gulp --version

Now that you have the prerequisites installed, you can fetch and build the UI project.

=== Clone and Initialize the UI Project

Clone this repository using git:

[subs=attributes+]
 $ git clone <repo-url> &&
   cd "`basename $_`"

Stay in this project folder when executing all subsequent commands.

Use npm to install the project's dependencies inside the project.
In your terminal, execute the following command:

 $ npm ci

This command installs the dependencies listed in [.path]_package.json_ into the [.path]_node_modules/_ folder inside the project.
This folder does not get included in the UI bundle and should _not_ be committed to the source control repository.

If you prefer, you can use `npm install`, but `npm ci` is recommended for reproducible installs.

=== Preview the UI

The default UI project is configured to preview offline.
The files in the [.path]_preview-src/_ folder provide the sample content that allow you to see the UI in action.
In this folder, you'll primarily find pages written in AsciiDoc.
These pages provide a representative sample and kitchen sink of content from the real site.

To build the UI and preview it in a local web server, run the `preview` command:

 $ gulp preview

You'll see a URL listed in the output of this command:

....
[12:00:00] Starting server...
[12:00:00] Server started http://localhost:5252
[12:00:00] Running server
....

Navigate to this URL to preview the site locally.

While this command is running, any changes you make to the source files will be instantly reflected in the browser.
This works by monitoring the project for changes, running the `preview:build` task if a change is detected, and sending the updates to the browser.

Press kbd:[Ctrl+C] to stop the preview server and end the continuous build.

=== Package for Use with Antora

If you need to package the UI so you can use it to generate the documentation site locally, run the following command:

 $ gulp bundle

If any errors are reported by lint, you'll need to fix them.

When the command completes successfully, the UI bundle will be available at [.path]_build/ui-bundle.zip_.
You can point Antora at this bundle using the `--ui-bundle-url` command-line option.

If you have the preview running, and you want to bundle without causing the preview to be clobbered, use:

 $ gulp bundle:pack

The UI bundle will again be available at [.path]_build/ui-bundle.zip_.

==== Source Maps

The build consolidates all the CSS and client-side JavaScript into combined files, [.path]_site.css_ and [.path]_site.js_, respectively, in order to reduce the size of the bundle.
{url-source-maps}[Source maps] correlate these combined files with their original sources.

This "`source mapping`" is accomplished by generating additional map files that make this association.
These map files sit adjacent to the combined files in the build folder.
The mapping they provide allows the debugger to present the original source rather than the obfuscated file, an essential tool for debugging.

In preview mode, source maps are enabled automatically, so there's nothing you have to do to make use of them.
If you need to include source maps in the bundle, you can do so by setting the `SOURCEMAPS` environment variable to `true` when you run the bundle command:

 $ SOURCEMAPS=true gulp bundle

In this case, the bundle will include the source maps, which can be used for debugging your production site.
