= Template Customization

The default UI bundle can be customized using AsciiDoc attributes.
xref:templates.adoc[] explains how to access such attributes.
But what are the attributes that actually used by the templates.
If you're going to use the default UI bundle for your project, you'll want to know.

== page-layout attribute

The `page-layout` attribute is defined per-page and tells Antora which layout to use.
This UI also appends the layout name to the `<body>` tag as a class, which makes it easy to target layouts in CSS.

A common use of the `page-layout` attribute is to select the `article` layout for blog posts.

[,asciidoc]
----
= Blog Post Title
:page-layout: article

Your blog post content starts here.
----

The resulting HTML will include a `<body>` class that matches the layout, allowing layout-specific styling.

== page-pagination attribute

The `page-pagination` attribute is set in your xref:antora:playbook:asciidoc-attributes.adoc[playbook] in order to enable pagination, if your UI bundle supports it.
The default UI bundle supports this and you'll get the links to previous and next pages at the bottom of every page, based your navigation.

.Enable pagination
[,yaml]
----
asciidoc:
  attributes:
    page-pagination: ''
----

Antora automatically calculates the appropriate URLs and inserts the correct links.

Since you most likely want this enabled for every page in your site, there's no point setting this attribute per page.
However, if you do want to be able to override it per page, such as to turn it off, then you need to soft set the value in the playbook.

.Enable pagination, but make it overridable
[,yaml]
----
asciidoc:
  attributes:
    page-pagination: '@'
----

You can now turn page pagination off by unsetting the `page-pagination` attribute in the document header.

== page-toctitle attribute

By default, the title (i.e., heading) text for the automatic TOC in the right-hand sidebar of the page is `Contents`.
You can set the `page-toctitle` page attribute in the page header to customize this text for a given page.

NOTE: Antora does not use the built-in `toctitle` attribute from AsciiDoc.

.Customize the TOC title for a page
[,asciidoc]
----
= Page Title
:page-toctitle: Outline

== Section Title

Paragraph text.
----

You can define this value in the playbook to set it globally.

.Customize the TOC title for all pages
[,yaml]
----
asciidoc:
  attributes:
    page-toctitle: Outline
----

Alternately, you can override the [.path]_toc.hbs_ template if you want to hard-code the value, consult a different attribute, or change the defaut value.

== page-toclevels attribute

By default, the the automatic TOC in the right-hand sidebar of the page shows two levels of headings.
You can set the `page-toclevels` page attribute in the page header to customize this depth for a given page.

NOTE: Antora does not use the built-in `toclevels` attribute from AsciiDoc.

.Customize the TOC levels for a page
[,asciidoc]
----
= Page Title
:page-toclevels: 1

== Section Title

Paragraph text.
----

You can define this value in the playbook to set it globally.

.Customize the TOC title for all pages
[,yaml]
----
asciidoc:
  attributes:
    page-toclevels: 1
----

Alternately, you can override the [.path]_toc.hbs_ template if you want to hard-code the value, consult a different attribute, or change the default value.
