site:
  title: Test Site
  url: http://localhost
  start_page: test::index.adoc

antora:
  extensions:
    - require: ./extensions/antora-tldr-ui.js
      shiki:
        lightTheme: github-light
        darkTheme: github-dark
      asciidoc:
        direct_icon_urls:
          pkl: https://raw.githubusercontent.com/apple/pkl-lang.org/refs/heads/main/src/supplemental-ui/img/favicon.svg
          toml: https://raw.githubusercontent.com/toml-lang/toml/refs/heads/main/logos/toml.svg

content:
  sources:
    - url: ..
      branches: HEAD
      start_path: test-antora/docs

ui:
  bundle:
    url: https://github.com/timothysparg/tldr-ui/releases/download/beta/ui-bundle.zip
    snapshot: true

output:
  dir: ./build/site
